komac update --identifier iamscottxu.obs-rtspserver --version 3.1.0 --urls https://github.com/iamscottxu/obs-rtspserver/releases/download/v3.1.0/obs-rtspserver-v3.1.0-windows-installer.exe --submit --token
komac update --identifier Terrastruct.D2 --version 0.6.3 --urls https://github.com/terrastruct/d2/releases/download/v0.6.3/d2-v0.6.3-windows-amd64.msi --submit --token
komac update --identifier ThePyzoteam.pyzo --version 4.14.4 --urls https://github.com/pyzo/pyzo/releases/download/v4.14.4/pyzo-4.14.4-win64.exe --submit --token
komac update --identifier foamzou.media-get --version 0.2.13 --urls https://github.com/foamzou/media-get/releases/download/v0.2.13/media-get-0.2.13-win.exe --submit --token
komac update --identifier Adobe.Cryptr --version 0.6.0 --urls https://github.com/adobe/cryptr/releases/download/v0.6.0/Cryptr.Setup.0.6.0.exe --submit --token
komac update --identifier JanetLang.Janet --version 1.33.0 --urls https://github.com/janet-lang/janet/releases/download/v1.33.0/janet-1.33.0-windows-x64-installer.msi --submit --token
komac update --identifier JaydenDev.Catalyst --version 3.5.4 --urls https://github.com/CatalystDevOrg/Catalyst/releases/download/v3.5.4/catalyst-3.5.4.Setup.exe --submit --token
komac update --identifier fzf404.Monit --version 0.8.1 --urls https://github.com/fzf404/Monit/releases/download/v0.8.1/Monit-0.8.1-win-x64.exe --submit --token
komac update --identifier D4koon.WhatsappTray --version 1.9.0 --urls https://github.com/D4koon/WhatsappTray/releases/download/v1.9.0/WhatsappTrayV1.9.0.0.exe --submit --token
komac update --identifier YikuanSun.WebKitty --version 3.2.1 --urls https://github.com/yikuansun/webkitty/releases/download/v3.2.1/WebKitty.Setup.3.2.1.exe --submit --token
komac update --identifier NitrokeyGmbH.Nitrokey-App --version 2.2.1 --urls https://github.com/Nitrokey/nitrokey-app2/releases/download/v2.2.1/nitrokey-app-v2.2.1-x64-windows-installer.msi --submit --token
komac update --identifier AlDanial.Cloc --version 2.00 --urls https://github.com/AlDanial/cloc/releases/download/v2.00/cloc-2.00.exe --submit --token
komac update --identifier Tillitis.TKeySSHAgent --version 0.0.6 --urls https://github.com/tillitis/tkey-ssh-agent/releases/download/v0.0.6/tkey-ssh-agent-0.0.6.0.msi --submit --token
komac update --identifier antonreshetov.massCode --version 3.11.0 --urls https://github.com/massCodeIO/massCode/releases/download/v3.11.0/massCode.Setup.3.11.0.exe --submit --token
komac update --identifier OVRASTeam.OpenVR-AdvancedSettings --version 5.8.6 --urls https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/releases/download/v5.8.6/AdvancedSettings-5.8.6-Installer.exe --submit --token
komac update --identifier flxzt.rnote --version 0.10.0 --urls https://github.com/flxzt/rnote/releases/download/v0.10.0/rnote-win-installer-0.10.0-x86_64.exe --submit --token
komac update --identifier TeraTermProject.teraterm5 --version 5.2 --urls https://github.com/TeraTermProject/teraterm/releases/download/v5.2/teraterm-5.2.exe --submit --token
komac update --identifier ETHZurich.SafeExamBrowser --version 3.6.0 --urls https://github.com/SafeExamBrowser/seb-win-refactoring/releases/download/v3.6.0/SEB_3.6.0.633_SetupBundle.exe --submit --token
komac update --identifier NitrokeyGmbH.Nitropy --version 0.4.45 --urls https://github.com/Nitrokey/pynitrokey/releases/download/v0.4.45/nitropy-v0.4.45-x64-windows-installer.msi --submit --token
komac update --identifier OwlbearRodeo.Kenku-FM --version 1.4.3 --urls https://github.com/owlbear-rodeo/kenku-fm/releases/download/v1.4.3/kenku-fm-1.4.3-win32-x64.exe --submit --token
komac update --identifier rsjaffe.MIDI2LR --version 6.1.0.0 --urls https://github.com/rsjaffe/MIDI2LR/releases/download/v6.1.0.0/MIDI2LR-6.1.0.0-windows-installer.exe --submit --token
komac update --identifier NicolasRamz.React-Explorer --version 3.1.0 --urls https://github.com/warpdesign/react-explorer/releases/download/v3.1.0/react-explorer-3.1.0-windows-universal-setup.exe --submit --token
komac update --identifier huanghongxun.HelloMinecraftLauncher --version 3.5.5.238 --urls https://github.com/HMCL-dev/HMCL/releases/download/v3.5.5.238/HMCL-3.5.5.238.exe --submit --token
komac update --identifier mar10.stressor --version 0.5.2 --urls https://github.com/mar10/stressor/releases/download/v0.5.2/stressor-0.5.2.0-win64.msi --submit --token
komac update --identifier JaydenDev.Catalyst3 --version 3.5.4 --urls https://github.com/CatalystDevOrg/Catalyst/releases/download/v3.5.4/catalyst-3.5.4.Setup.exe --submit --token
komac update --identifier mar10.wsgidav --version 4.3.0 --urls https://github.com/mar10/wsgidav/releases/download/v4.3.0/WsgiDAV-4.3.0.0-win64.msi --submit --token
komac update --identifier nomic.gpt4all --version 2.7.1 --urls https://github.com/nomic-ai/gpt4all/releases/download/v2.7.1/gpt4all-installer-win64-v2.7.1.exe --submit --token
komac update --identifier listen1.listen1.fluent --version 2.28.0 --urls https://github.com/reycn/listen1-desktop-fluent/releases/download/v2.28.0/listen1_2.28.0_win_x64.exe --submit --token
komac update --identifier Adamant.Messenger --version 4.5.3 --urls https://github.com/Adamant-im/adamant-im/releases/download/v4.5.3/ADAMANT.Messenger.Setup.4.5.3.exe --submit --token
komac update --identifier NexusMods.Vortex --version 1.9.12 --urls https://github.com/Nexus-Mods/Vortex/releases/download/v1.9.12/vortex-setup-1.9.12.exe --submit --token
komac update --identifier ThioJoe.YTSpammerPurge --version 2.17.1 --urls https://github.com/ThioJoe/YT-Spammer-Purge/releases/download/v2.17.1/YTSpammerPurge.2.17.1.exe --submit --token
komac update --identifier mar10.pyftpsync --version 4.0.0 --urls https://github.com/mar10/pyftpsync/releases/download/v4.0.0/pyftpsync-4.0.0.0-win64.msi --submit --token
komac update --identifier mscststs.LANService --version 0.0.5 --urls https://github.com/mscststs/LANService/releases/download/v0.0.5/LANService.Setup.1.0.5.exe --submit --token
komac update --identifier Intel.OSPRay --version 3.1.0 --urls https://github.com/ospray/ospray/releases/download/v3.1.0/ospray-3.1.0.x86_64.windows.msi --submit --token
komac update --identifier trinsic.cli --version 1.13.0 --urls https://github.com/trinsic-id/sdk/releases/download/v1.13.0/trinsic-cli-1.13.0-x86_64.msi --submit --token
komac update --identifier PTRTECH.UVtools --version 4.2.4 --urls https://github.com/sn4k3/UVtools/releases/download/v4.2.4/UVtools_win-x64_v4.2.4.msi --submit --token
komac update --identifier PowerClouds.CertoNiuchacz --version 2.0.1 --urls https://github.com/mgajda83/CertoNiuchacz/releases/download/v2.0.1/CertoNiuchacz_2.0.1.0_x64__4tr01tz8fz8e6.msix --submit --token
komac update --identifier QGIS.QField --version 3.1.9 --urls https://github.com/opengisch/QField/releases/download/v3.1.9/qfield-v3.1.9-windows-x64.exe --submit --token
komac update --identifier TeraTermProject.teraterm --version 5.2 --urls https://github.com/TeraTermProject/teraterm/releases/download/v5.2/teraterm-5.2.exe --submit --token
komac update --identifier WerWolv.ImHex --version 1.33.1 --urls https://github.com/WerWolv/ImHex/releases/download/v1.33.1/imhex-1.33.1-Windows-x86_64.msi --submit --token
komac update --identifier CiderCollective.Cider --version 1.6.2 --urls https://github.com/ciderapp/Cider/releases/download/v1.6.2/Cider-Setup-1.6.2.exe --submit --token
komac update --identifier EnderbytePrograms.TimeIt --version 1.3 --urls https://github.com/Enderbyte-Programs/WinTimeIt/releases/download/v1.3/wintimeit-1.3-setup.exe --submit --token
komac update --identifier JackHumphries.Socially --version 1.0 --urls https://github.com/JackHumphries9/Socially/releases/download/V1.0/Socially-Windows_1.0.0-amd64.exe --submit --token
komac update --identifier g07cha.pomodoro --version 3.5.0 --urls https://github.com/G07cha/pomodoro/releases/download/v3.5.0/Pomodoro_3.5.0_x64-setup.exe --submit --token
komac update --identifier svenstaro.genact --version 1.4.2 --urls https://github.com/svenstaro/genact/releases/download/v1.4.2/genact-1.4.2-x86_64-pc-windows-msvc.exe --submit --token
komac update --identifier Carmix.HexWalk --version 1.7.1 --urls https://github.com/gcarmix/HexWalk/releases/download/v1.7.1/HexWalk_1.7.1_Windows_X64_Installer.exe --submit --token
komac update --identifier Pulsar-Edit.Pulsar --version 1.114.0 --urls https://github.com/pulsar-edit/pulsar/releases/download/v1.114.0/Windows.Pulsar.Setup.1.114.0.exe --submit --token
komac update --identifier Tetrate.wazero --version 1.6.0 --urls https://github.com/tetratelabs/wazero/releases/download/v1.6.0/wazero_1.6.0_windows_amd64.msi --submit --token
komac update --identifier ArduinoSA.CLI --version 0.35.3 --urls https://github.com/arduino/arduino-cli/releases/download/v0.35.3/arduino-cli_0.35.3_Windows_64bit.msi --submit --token
komac update --identifier StarlaneStudios.Surrealist --version 1.11.5 --urls https://github.com/StarlaneStudios/Surrealist/releases/download/v1.11.5/surrealist-v1.11.5-windows.msi --submit --token
komac update --identifier AMD.OCAT --version 1.6.3 --urls https://github.com/GPUOpen-Tools/ocat/releases/download/v1.6.3/OCAT_v1.6.3.exe --submit --token
komac update --identifier akeo.ie.Zadig --version 1.5.0 --urls https://github.com/pbatard/libwdi/releases/download/v1.5.0/zadig-2.8.exe --submit --token
komac update --identifier Exploitox.WebRadio --version 1.0.0 --urls https://github.com/valnoxy/WebRadio/releases/download/v1.0.0/WebRadio_1.0.0.38_x64.exe --submit --token
komac update --identifier OpenHPSDR-TAPR.PowerSDR --version 3.4.9 --urls https://github.com/TAPR/OpenHPSDR-PowerSDR/releases/download/v3.4.9/PowerSDR_mRX_PS_v3.4.9.0_Setup.msi --submit --token