komac update --identifier Adobe.Cryptr --version 0.6.0 --urls https://github.com/adobe/cryptr/releases/download/v0.6.0/Cryptr.Setup.0.6.0.exe --submit --token
komac update --identifier nomic.gpt4all --version 2.7.1 --urls https://github.com/nomic-ai/gpt4all/releases/download/v2.7.1/gpt4all-installer-win64-v2.7.1.exe --submit --token
komac update --identifier trinsic.cli --version 1.13.0 --urls https://github.com/trinsic-id/sdk/releases/download/v1.13.0/trinsic-cli-1.13.0-x86_64.msi --submit --token
komac update --identifier Exploitox.WebRadio --version 1.0.0 --urls https://github.com/valnoxy/WebRadio/releases/download/v1.0.0/WebRadio_1.0.0.38_x64.exe --submit --token
komac update --identifier StarlaneStudios.Surrealist --version 1.11.5 --urls https://github.com/StarlaneStudios/Surrealist/releases/download/v1.11.5/surrealist-v1.11.5-windows.msi --submit --token
komac update --identifier Intel.OSPRay --version 3.1.0 --urls https://github.com/ospray/ospray/releases/download/v3.1.0/ospray-3.1.0.x86_64.windows.msi --submit --token
komac update --identifier EnderbytePrograms.TimeIt --version 1.3 --urls https://github.com/Enderbyte-Programs/WinTimeIt/releases/download/v1.3/wintimeit-1.3-setup.exe --submit --token
komac update --identifier TeraTermProject.teraterm --version 5.2 --urls https://github.com/TeraTermProject/teraterm/releases/download/v5.2/teraterm-5.2.exe --submit --token
komac update --identifier D4koon.WhatsappTray --version 1.9.0 --urls https://github.com/D4koon/WhatsappTray/releases/download/v1.9.0/WhatsappTrayV1.9.0.0.exe --submit --token
komac update --identifier foamzou.media-get --version 0.2.13 --urls https://github.com/foamzou/media-get/releases/download/v0.2.13/media-get-0.2.13-win.exe --submit --token
komac update --identifier NitrokeyGmbH.Nitrokey-App --version 2.2.1 --urls https://github.com/Nitrokey/nitrokey-app2/releases/download/v2.2.1/nitrokey-app-v2.2.1-x64-windows-installer.msi --submit --token
komac update --identifier iamscottxu.obs-rtspserver --version 3.1.0 --urls https://github.com/iamscottxu/obs-rtspserver/releases/download/v3.1.0/obs-rtspserver-v3.1.0-windows-installer.exe --submit --token
komac update --identifier ETHZurich.SafeExamBrowser --version 3.6.0 --urls https://github.com/SafeExamBrowser/seb-win-refactoring/releases/download/v3.6.0/SEB_3.6.0.633_SetupBundle.exe --submit --token
komac update --identifier Tetrate.wazero --version 1.6.0 --urls https://github.com/tetratelabs/wazero/releases/download/v1.6.0/wazero_1.6.0_windows_amd64.msi --submit --token
komac update --identifier listen1.listen1.fluent --version 2.28.0 --urls https://github.com/reycn/listen1-desktop-fluent/releases/download/v2.28.0/listen1_2.28.0_win_x64.exe --submit --token
komac update --identifier TeraTermProject.teraterm5 --version 5.2 --urls https://github.com/TeraTermProject/teraterm/releases/download/v5.2/teraterm-5.2.exe --submit --token
komac update --identifier FredEmmott.OpenKneeboard --version 1.7.0 --urls https://github.com/OpenKneeboard/OpenKneeboard/releases/download/v1.7.0/OpenKneeboard-v1.7.0.msi --submit --token
komac update --identifier PowerClouds.CertoNiuchacz --version 2.0.1 --urls https://github.com/mgajda83/CertoNiuchacz/releases/download/v2.0.1/CertoNiuchacz_2.0.1.0_x64__4tr01tz8fz8e6.msix --submit --token
komac update --identifier OpenHPSDR-TAPR.PowerSDR --version 3.4.9 --urls https://github.com/TAPR/OpenHPSDR-PowerSDR/releases/download/v3.4.9/PowerSDR_mRX_PS_v3.4.9.0_Setup.msi --submit --token
komac update --identifier JanetLang.Janet --version 1.33.0 --urls https://github.com/janet-lang/janet/releases/download/v1.33.0/janet-1.33.0-windows-x64-installer.msi --submit --token
komac update --identifier akeo.ie.Zadig --version 1.5.0 --urls https://github.com/pbatard/libwdi/releases/download/v1.5.0/zadig-2.8.exe --submit --token
komac update --identifier Tillitis.TKeySSHAgent --version 0.0.6 --urls https://github.com/tillitis/tkey-ssh-agent/releases/download/v0.0.6/tkey-ssh-agent-0.0.6.0.msi --submit --token
komac update --identifier LGUG2Z.komorebi --version 0.1.22 --urls https://github.com/LGUG2Z/komorebi/releases/download/v0.1.22/komorebi-0.1.22-x86_64.msi --submit --token
komac update --identifier mar10.pyftpsync --version 4.0.0 --urls https://github.com/mar10/pyftpsync/releases/download/v4.0.0/pyftpsync-4.0.0.0-win64.msi --submit --token
komac update --identifier UniversityOfEdinburgh.QuPath --version 0.5.1 --urls https://github.com/qupath/qupath/releases/download/v0.5.1/QuPath-v0.5.1-Windows.msi --submit --token
komac update --identifier JackHumphries.Socially --version 1.0 --urls https://github.com/JackHumphries9/Socially/releases/download/V1.0/Socially-Windows_1.0.0-amd64.exe --submit --token
komac update --identifier NitrokeyGmbH.Nitropy --version 0.4.45 --urls https://github.com/Nitrokey/pynitrokey/releases/download/v0.4.45/nitropy-v0.4.45-x64-windows-installer.msi --submit --token
komac update --identifier JaydenDev.Catalyst3 --version 3.5.4 --urls https://github.com/CatalystDevOrg/Catalyst/releases/download/v3.5.4/catalyst-3.5.4.Setup.exe --submit --token
komac update --identifier rsjaffe.MIDI2LR --version 6.1.0.0 --urls https://github.com/rsjaffe/MIDI2LR/releases/download/v6.1.0.0/MIDI2LR-6.1.0.0-windows-installer.exe --submit --token
komac update --identifier mar10.wsgidav --version 4.3.0 --urls https://github.com/mar10/wsgidav/releases/download/v4.3.0/WsgiDAV-4.3.0.0-win64.msi --submit --token
komac update --identifier AMD.OCAT --version 1.6.3 --urls https://github.com/GPUOpen-Tools/ocat/releases/download/v1.6.3/OCAT_v1.6.3.exe --submit --token
komac update --identifier mscststs.LANService --version 0.0.5 --urls https://github.com/mscststs/LANService/releases/download/v0.0.5/LANService.Setup.1.0.5.exe --submit --token
komac update --identifier Iminetsoft.DarkSwitcher --version 1.2.8463 --urls https://github.com/iminet/DarkSwitcher/releases/download/v1.2.8463/DarkSwitcher.1.2.8463.setup.exe --submit --token
komac update --identifier mar10.stressor --version 0.5.2 --urls https://github.com/mar10/stressor/releases/download/v0.5.2/stressor-0.5.2.0-win64.msi --submit --token