# Example Configuration Template for WinGet Manifest Automation Tool
# Copy this file to config.yaml and customize it for your specific needs.
#
# To use this configuration:
# 1. Copy this file to config/config.yaml
# 2. Set the ENVIRONMENT environment variable (development/staging/production)
# 3. Set GitHub tokens via GITHUB_TOKENS environment variable (comma-separated)

# Environment setting (can be overridden via ENVIRONMENT env var)
environment: development  # Options: development, staging, production
debug: true

# GitHub API configuration
github:
  api_url: "https://api.github.com"
  tokens: []  # Add via GITHUB_TOKENS environment variable (comma-separated)
  per_page: 100
  retry_attempts: 3
  retry_delay: 1.0
  rate_limit_buffer: 100

# Package processing configuration
package_processing:
  winget_repo_path: "winget-pkgs"
  output_directory: "data"
  batch_size: 100
  max_workers: 4
  timeout: 300
  file_patterns:
    - "*.installer.yaml"
    - "*.locale.yaml"
    - "*.portable.yaml"

# Filtering configuration
filtering:
  blocked_packages: []  # Add package IDs to block
  allowed_architectures:
    - "x64"
    - "x86"
    - "arm64"
  allowed_extensions:
    - "msi"
    - "exe"
    - "zip"
    - "msix"
    - "appx"
  min_download_count: 0
  max_package_age_days: 365

# Output configuration
output:
  formats:
    - "csv"
  compression: "none"
  include_metadata: true
  timestamp_format: "%Y%m%d_%H%M%S"
  csv:
    delimiter: ","
    quote_char: '"'
    encoding: "utf-8"

# Performance configuration
performance:
  cache_ttl: 3600
  memory_limit_mb: 1024
  enable_profiling: false
  requests_per_second: 10
  burst_limit: 50

# Logging configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: null  # Set to file path for file logging
  max_size: 10  # MB
  backup_count: 5

# Environment-specific overrides
environments:
  development:
    debug: true
    logging:
      level: "DEBUG"
    performance:
      cache_ttl: 300
      batch_size: 10
      
  production:
    debug: false
    logging:
      level: "WARNING"
      file: "logs/production.log"
    performance:
      memory_limit_mb: 2048
  timeout: 300  # Timeout in seconds for each operation

# Filtering configuration
filtering:
  # Packages to exclude from processing
  blocked_packages:
    - "Microsoft.VisualStudioCode.Insiders"
    - "TestPackage.BlockedPackage"
  
  # Allowed architectures
  allowed_architectures:
    - "x64"
    - "x86"
    - "arm64"
    - "arm"
    - "aarch64"
    - "x86_64"
    - "any"
    - "neutral"
  
  # Allowed file extensions
  allowed_extensions:
    - "msi"
    - "exe"
    - "zip"
    - "7z"
    - "msix"
    - "appx"
    - "msixbundle"
    - "appxbundle"
  
  # Filtering thresholds
  min_download_count: 0  # Minimum GitHub download count
  max_package_age_days: 365  # Maximum age of package releases

# Output configuration
output:
  formats:
    - "csv"
    - "json"
  compression: "gzip"  # none, gzip, bz2, xz
  include_metadata: true
  timestamp_format: "%Y%m%d_%H%M%S"

# Performance configuration
performance:
  cache_enabled: true
  cache_ttl: 7200  # Cache time-to-live in seconds (2 hours)
  memory_limit_mb: 2048  # Memory limit in MB
  enable_profiling: false  # Enable performance profiling

# Example environment variable usage:
# 
# Set these environment variables to override configuration:
# export WINGET_ENV=development
# export TOKEN_1=your_github_token_here
# export TOKEN_2=your_second_github_token_here
# export LOG_LEVEL=INFO
# export MAX_WORKERS=8
# export BATCH_SIZE=200
# export CACHE_ENABLED=true
