# Unified Configuration for WinGet Manifest Automation Tool
# This single configuration file contains all settings for the tool.
# Environment-specific overrides can be set via environment variables.

# Environment settings (can be overridden via ENVIRONMENT env var)
environment: production  # Options: development, staging, production
debug: false  # Set to true for verbose output

# GitHub API configuration
github:
  api_url: "https://api.github.com"
  # GitHub tokens are loaded from environment variables in this order:
  # 1. GITHUB_TOKENS (comma-separated list)
  # 2. GITHUB_TOKEN (single token)  
  # 3. TOKEN_1, TOKEN_2, TOKEN_3 (individual tokens)
  # Store tokens in .env file for security
  tokens: []  # Will be populated from environment variables
  per_page: 100
  retry_attempts: 3
  retry_delay: 1.0
  rate_limit_buffer: 100

# Package processing configuration
package_processing:
  winget_repo_path: "winget-pkgs"
  output_directory: "data"
  batch_size: 1000
  max_workers: 32
  max_concurrent_files: 1500  # For async operations
  use_async: true  # Enable async processing for better performance
  timeout: 300
  file_patterns:
    - "*.installer.yaml"
    - "*.locale.yaml"
    - "*.portable.yaml"

# Filtering configuration
filtering:
  # Package blocklist
  blocked_packages:
    - "ojdkbuild.openjdk.13.jdk"
    - "ojdkbuild.openjdk.11.jdk"
    - "ojdkbuild.openjdk.17.jdk"
    - "ojdkbuild.openjdk.11.jre"
    - "ojdkbuild.openjdk.14.jdk"
    - "ojdkbuild.openjdk.17.jre"
    - "BtbN.FFmpeg.LGPL.Shared.6.1"
    - "BtbN.FFmpeg.LGPL.Shared.7.1"
    - "BtbN.FFmpeg.GPL.Shared.6.1"
    - "BtbN.FFmpeg.GPL.Shared.7.1"
    - "BtbN.FFmpeg.GPL"
    - "BtbN.FFmpeg.LGPL.Shared"
    - "BtbN.FFmpeg.GPL.7.1"
    - "BtbN.FFmpeg.GPL.Shared"
    - "BtbN.FFmpeg.LGPL.6.1"
    - "BtbN.FFmpeg.LGPL.5.1"
    - "BtbN.FFmpeg.LGPL"
    - "BtbN.FFmpeg.GPL.6.1"
    - "BtbN.FFmpeg.LGPL.Shared.5.1"
    - "BtbN.FFmpeg.GPL.Shared.5.1"
    - "BtbN.FFmpeg.LGPL.7.1"
    - "BtbN.FFmpeg.GPL.5.1"
    - "IBM.Semeru.16.JRE"
    - "IBM.Semeru.16.JDK"
    - "AdoptOpenJDK.OpenJDK.16"
    - "AdoptOpenJDK.OpenJDK.8"
    - "ChrisRizzitello.BlackChocobo"
    - "LiteXLTeam.LPM"
    - "IBM.Semeru.11.JDK"
    - "IBM.Semeru.11.JRE"
  
  # Supported architectures
  allowed_architectures:
    - "x64"
    - "x86"
    - "arm64"
    - "arm"
    - "aarch64"
    - "x86_64"
    - "any"
    - "neutral"
  
  # Supported file extensions
  allowed_extensions:
    - "msi"
    - "exe"
    - "zip"
    - "7z"
    - "rar"
    - "tar.gz"
    - "tar.bz2"
    - "msix"
    - "appx"
    - "msixbundle"
    - "appxbundle"
    - "deb"
    - "rpm"
    - "pkg"
    - "dmg"
  
  # Minimum download count to include package
  min_download_count: 0
  
  # Maximum age of package releases to include (in days)
  max_package_age_days: 365

# Output configuration
output:
  formats:
    - "csv"
  compression: "none"
  include_metadata: true
  timestamp_format: "%Y%m%d_%H%M%S"
  
  # CSV specific settings
  csv:
    delimiter: ","
    quote_char: '"'
    escape_char: "\\"
    encoding: "utf-8"

# Performance configuration
performance:
  cache_ttl: 3600  # 1 hour default
  memory_limit_mb: 1024
  enable_profiling: false
  requests_per_second: 10
  burst_limit: 50

# Logging configuration
logging:
  level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"
  file: null  # Set to file path for file logging
  max_size: 10  # MB
  backup_count: 5

# Environment-specific overrides (applied when environment is set)
environments:
  development:
    debug: true
    logging:
      level: "DEBUG"
      file: null
    performance:
      enable_profiling: true
      cache_ttl: 300  # 5 minutes for faster development
    package_processing:
      batch_size: 10  # Smaller batches for debugging
      max_workers: 2
  
  staging:
    debug: false
    logging:
      level: "INFO"
      file: "logs/staging.log"
    performance:
      cache_ttl: 1800  # 30 minutes
      
  production:
    debug: false
    logging:
      level: "WARNING"
      file: "logs/production.log"
    performance:
      cache_ttl: 3600  # 1 hour
      memory_limit_mb: 2048
