# WinGet Manifest Generator Tool Configuration

# Environment: production
# This configuration is optimized for production environment with high
# performance settings and WARNING level logging for minimal overhead.

environment: production
debug: false

# Logging configuration
logging:
  level: WARNING
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/winget-automation-production.log"
  max_size: 100  # MB
  backup_count: 20

# GitHub API configuration
github:
  tokens: []  # Add your GitHub tokens via environment variables
  api_url: "https://api.github.com"
  per_page: 100
  retry_attempts: 10
  retry_delay: 5.0
  rate_limit_buffer: 500

# Package processing configuration
package_processing:
  winget_repo_path: "winget-pkgs"
  output_directory: "data"
  file_patterns:
    - "*.installer.yaml"
  max_workers: 8
  batch_size: 500
  timeout: 600

# Filtering configuration
filtering:
  blocked_packages: []
  allowed_architectures:
    - "x64"
    - "x86"
    - "arm64"
    - "arm"
    - "aarch64"
    - "x86_64"
  allowed_extensions:
    - "msi"
    - "exe"
    - "zip"
    - "msix"
    - "appx"
    - "msixbundle"
    - "appxbundle"
  min_download_count: 0
  max_package_age_days: 365

# Output configuration
output:
  formats:
    - "csv"
    - "json"
    - "parquet"
  compression: "gzip"
  include_metadata: true
  timestamp_format: "%Y%m%d_%H%M%S"

# Performance configuration
performance:
  cache_enabled: true
  cache_ttl: 14400  # 4 hours
  memory_limit_mb: 4096
  enable_profiling: false

# Monitoring configuration
monitoring:
  metrics_enabled: true
  max_timer_history: 1000
  max_metric_history: 10000
  health_check_interval: 300
  export_metrics_interval: 1800
  progress:
    console_output: false  # Disabled in production for cleaner logs
    log_updates: true
    update_interval: 2.0

# Service information
service:
  name: "winget-automation"
  version: "1.0.0"
