# WinGetManifestAutomationTool Configuration

# Environment: staging
# This configuration is optimized for staging environment with moderate
# performance settings and INFO level logging.

environment: staging
debug: false

# Logging configuration
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/winget-automation-staging.log"
  max_size: 50  # MB
  backup_count: 10

# GitHub API configuration
github:
  tokens: []  # Add your GitHub tokens via environment variables
  api_url: "https://api.github.com"
  per_page: 100
  retry_attempts: 5
  retry_delay: 2.0
  rate_limit_buffer: 200

# Package processing configuration
package_processing:
  winget_repo_path: "winget-pkgs"
  output_directory: "data"
  file_patterns:
    - "*.installer.yaml"
  max_workers: 4
  batch_size: 100
  timeout: 300

# Filtering configuration
filtering:
  blocked_packages: []
  allowed_architectures:
    - "x64"
    - "x86"
    - "arm64"
    - "arm"
    - "aarch64"
    - "x86_64"
  allowed_extensions:
    - "msi"
    - "exe"
    - "zip"
    - "msix"
    - "appx"
    - "msixbundle"
    - "appxbundle"
  min_download_count: 0
  max_package_age_days: 365

# Output configuration
output:
  formats:
    - "csv"
    - "json"
  compression: "gzip"
  include_metadata: true
  timestamp_format: "%Y%m%d_%H%M%S"

# Performance configuration
performance:
  cache_enabled: true
  cache_ttl: 7200  # 2 hours
  memory_limit_mb: 2048
  enable_profiling: false

# Monitoring configuration
monitoring:
  metrics_enabled: true
  max_timer_history: 1000
  max_metric_history: 10000
  health_check_interval: 120
  export_metrics_interval: 600
  progress:
    console_output: true
    log_updates: true
    update_interval: 1.0

# Service information
service:
  name: "winget-automation"
  version: "1.0.0"
